### PR TITLE
now stores json data in a single DF

### PR DESCRIPTION
**Pull request by Trenton-Serpas**
image

The data is now stored in a dataframe with all of the recursive call jsons merged into it

This also drops the use of future in the main

my one concern is the runtime is now a little long but I don't know what could be causing it

### CODE REVIEW

**Comment by spark131008** [comment]
Looks good to me. One minor thing, don't you think it will be more clear for outsiders to understand our code by changing the two "getTweets" methods' names into "getFirst10Tweets" and "getTheRestTweets".

**Comment by Trenton-Serpas** [comment]
> 
> 
> Looks good to me. One minor thing, don't you think it will be more clear for outsiders to understand our code by changing the two "getTweets" methods' names into "getFirst10Tweets" and "getTheRestTweets".

maybe but we can do that in a followup PR since its not in the code I touched in this PR

I think using polymorphism here isnt too bad of a design scheme

**Comment by spark131008** [comment]
then, i think we can merge this to main?

**Comment by Trenton-Serpas** [comment]
sounds good

**Pull request merged**
